name: Java CI with Gradle

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build_and_run:

    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'

    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@v4

    - name: Build Project
      run: ./gradlew build
      
    - name: Run First Test
      run: ./gradlew test --tests "org.example.MainTest"    
    
    - name: Run Second Test
      run: ./gradlew test --tests "org.example.SECONDTest"


    - name: Run Main Application
      run: java -jar build/libs/*.jar
